# libraries 
library(tidyverse)

# data 
data = read_csv("./raw_data/Are+you+Smarter__November+22,+2020_16.13.csv")

# make the first row the new colnames ####

colnames(data) = data[1,]

# select the columns needed
new_cols = c(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  "End Date",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  "I want to participate in this study (remember, you will get credit for participating whether you click yes or no because you already typed your name above):" ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  "Consent:  By typing my name, I confirm that    \tI have read and understood the information in this consent document; \tI will email the researchers to ask questions that I may have prior to giving my consent (if needed); \tI understand that my participation is voluntary and that I am free to withdraw at any time, without giving a reason and without cost or penalty to me; \tI give my instructor permission to give the researchers my grade on the first exam in this course;  \tI give the researchers permission to have access to my UVU GPA or my high school GPA if I don't have a current UVU GPA; \tI understand that I can print a copy of this consent form for my records;  \tI voluntarily agree to take part in this study; and \tI must type my full name below to receive credit for participating in this study.",
  "What percentage of students are you smarter than, if you consider only the students in this course and the course content?",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  "Do you tend to work with one person in this class more than others?",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  "If so, who?  Please enter their first and last name. If you can't remember both names, just enter the first name.",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  "Please choose the following to describe your interactions during peer discussions in class:",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  "After interacting with [QID3-ChoiceTextEntryValue] to this point in class, who do you feel is smarter?",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  "How did you determine who was smarter, you or [QID3-ChoiceTextEntryValue]? Please use 2-3 sentences in explaining your reasoning.",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  "What is your gender?",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  "uvid",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  "courseId",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  "courseName",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  "courseCrn",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  "courseSemester",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  "instructorFirstName",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
  "instructorLastName",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  "majorDescription",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  "minorDescription",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  "levelDescription" ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  "gender" 
  )


# keep only the selected columns 
data = data[ , new_cols]

# remove the first to rows (useless qualtrics data)
data == data[- c(1,2), ]

# filter out just for fall 2019 ####
data = data %>% filter(courseSemester == '201940')

# filter out students who didn't answer percentage smarter question
data = data %>% 
  filter(! is.na(`What percentage of students are you smarter than, if you consider only the students in this course and the course content?`)) 


# save the data 
write.csv(data, './analyzed_data/cleaned_survey_data_FALL_2019.csv', row.names = F) # survey data

classes = unique(data$courseName)

write.csv(classes, './raw_data/syllaby_needed_for_these.csv', row.names = F)






